version: '3.8'
services:
  tron-node1:
    extends:
      file: tron-node.yml
      service: tron-node

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    deploy:
      resources:
        limits:
          memory: 1g
    ports:
      - "9090:9090" # used for external collect metrics
    volumes:
      - ../conf:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus-quick-start.yml" # path to the configuration file

  grafana:
    extends:
      file: grafana.yml
      service: grafana
