services:
  vmstorage1:
    image: victoriametrics/vmstorage:latest
    command:
      - -retentionPeriod=1y
      - -httpListenAddr=:8482
      - -vminsertAddr=:8400
      - -vmselectAddr=:8401
    ports:
      - "8482:8482"
      - "8400:8400"
      - "8401:8401"
    volumes:
      - ./storage1-data:/vmstorage-data
    networks:
      - vm-cluster-net

  vmstorage2:
    image: victoriametrics/vmstorage:latest
    command:
      - -retentionPeriod=1y
      - -httpListenAddr=:8482
      - -vminsertAddr=:8400
      - -vmselectAddr=:8401
    ports:
      - "8483:8482"
      - "8402:8400"
      - "8403:8401"
    volumes:
      - ./storage2-data:/vmstorage-data
    networks:
      - vm-cluster-net

  vminsert:
    image: victoriametrics/vminsert:latest
    command:
      - -httpListenAddr=:8480
      - -storageNode=vmstorage1:8400,vmstorage2:8400
    ports:
      - "8480:8480"
    networks:
      - vm-cluster-net

  vmselect:
    image: victoriametrics/vmselect:latest
    command:
      - -search.latencyOffset=1s
      - -httpListenAddr=:8481
      - -storageNode=vmstorage1:8401,vmstorage2:8401
    ports:
      - "8481:8481"
    networks:
      - vm-cluster-net

networks:
  vm-cluster-net:
    driver: bridge