services:
  tron-node-nile:
    container_name: tron-node
    image: tronprotocol/java-tron:latest  # Add specific tag if needed
    mem_limit: 16g
    ports:
      - "8090:8090"
      - "8091:8091"
      - "18888:18888"
      - "18888:18888/udp"
      - "50051:50051"
    volumes:
      - ../conf:/java-tron/conf
      - ../logs/nile:/java-tron/logs
      - ../output-directory/nile:/java-tron/output-directory
    command:
      - -jvm
      - "{-Xmx14g -Xms12g -XX:+UseConcMarkSweepGC}"  # Using environment variable for JVM arguments
      - -c
      - /java-tron/conf/nile_net_config.conf
