services:
  tron-node-private:
    container_name: tron-witness1
    image: tronprotocol/java-tron:latest  # Add specific tag if needed
    mem_limit: 6g
    ports:
      - "8090:8090"
      - "8091:8091"
      - "18888:18888"
      - "18888:18888/udp"
      - "50051:50051"
    volumes:
      - ../conf:/java-tron/conf
      - ../logs/private:/java-tron/logs
      - ../output-directory/private:/java-tron/output-directory
    command:
      - -jvm
      - "{-Xmx4g -Xms2g -XX:+UseConcMarkSweepGC}"  # Using environment variable for JVM arguments
      - -c
      - /java-tron/conf/private_net_config_witness1.conf
      - -w
